services:
  k6:
    image: grafana/k6:1.1.0
    # command: run /scripts/test.js
    volumes:
      - ./k6/scripts:/scripts 
      - ./k6/output:/home/k6 
    networks:
      - default

networks:
  load-balancing-default:
    external: true
    driver: bridge